services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.0
    command:
      - start-dev
      - --import-realm
      - --http-port=8080
      - --proxy-headers=xforwarded
      - --truststore-paths=/opt/keycloak/conf/oid4vc-wallet-ca.pem
      - --tls-hostname-verifier=ANY
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info,de.arbeitsagentur:trace
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./providers:/opt/keycloak/providers:ro
      - ./wallet-ca-cert.pem:/opt/keycloak/conf/oid4vc-wallet-ca.pem:ro
      - ./realm:/opt/keycloak/data/import:ro
