services:
  keycloak:
    command:
      - start-dev
      - --import-realm
      - --features=oid4vc-vci:v1,oid4vc-vci-preauth-code:v1
      - --https-port=8443
      - --proxy-headers=xforwarded
      - --truststore-paths=/opt/keycloak/conf/keycloak-ca-cert.pem
      - --tls-hostname-verifier=ANY
      - --https-certificate-file=/opt/keycloak/conf/keycloak-cert.pem
      - --https-certificate-key-file=/opt/keycloak/conf/keycloak-key.pem
    ports:
      - "8443:8443"
    volumes:
      - ./keycloak-ca-cert.pem:/opt/keycloak/conf/keycloak-ca-cert.pem:ro
      - ./keycloak-cert.pem:/opt/keycloak/conf/keycloak-cert.pem:ro
      - ./keycloak-key.pem:/opt/keycloak/conf/keycloak-key.pem:ro
