services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.0
    command:
      - start-dev
      - --features=oid4vc-vci:v1,oid4vc-vci-preauth-code:v1
      - --http-port=8080
      - --proxy-headers=xforwarded
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info,de.arbeitsagentur:trace
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./providers:/opt/keycloak/providers:ro
